package golang_test

import (
	"testing"
	"time"

	_ "embed" // Tricky code.

	"github.com/faetools/format/golang"
	"github.com/stretchr/testify/assert"
	"golang.org/x/tools/imports"
)

//go:embed "tricky code.tpl"
var trickyCode []byte

const before = `// Code generated by test; DO NOT EDIT.
	package main

	var msg = "Hello World" // a comment
	var bar = "This line should be removed"




	// here is a comment
	const foo = "test"
	`

const after = `// Code generated by test; DO NOT EDIT.
package main

var (
	msg = "Hello World" // a comment
	bar = "This line should be removed"
)

// here is a comment
const foo = "test"
`

func TestFormat(t *testing.T) {
	t.Parallel()

	out, err := golang.Format("", []byte(before))
	assert.NoError(t, err)
	assert.Equal(t, after, string(out))
}

const waitTime = 6 * time.Second

func TestImports(t *testing.T) {
	t.Parallel()

	assert.NotEmpty(t, trickyCode)

	done := make(chan error)

	go func() {
		_, err := imports.Process("internal/httpservice/helpers.gen_test.go", trickyCode, nil)
		done <- err
	}()

	select {
	case <-time.After(waitTime):
		t.Fatal("never finishes")
	case err := <-done:
		assert.NoError(t, err)
	}
}
