// Code generated by devtool; DO NOT EDIT.
package format

import "github.com/Masterminds/semver/v3"

var (
	// Version is the version of format.
	Version = semver.MustParse("0.0.5")

	// GoVersion declares what version of Go should be used.
	GoVersion = semver.MustParse("1.17.8")
)
